name: marvelapp
description: Softwere Development Project IV.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  appbar_textfield: ^1.0.1+1
  connectivity: ^3.0.4
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  persistent_bottom_nav_bar: ^4.0.2
  photo_view: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.0.0
  equatable: ^2.0.0
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  flutter_bloc: ^7.0.0
  google_fonts: ^2.0.0
  html: ^0.15.0
  http: ^0.13.3
  url_launcher: ^6.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/